projects/mysite/home/urls.py
from django.conf.urls import url
from . import views
app_name='home'
urlpatterns=[
	url(r'^$',views.index, name='index'),
	url(r'^(?P<question_id>[0-9]+)/$',views.details, name='details'),
	url(r'^(?P<question_id>[0-9]+)/results/$',views.results, name='results'),
	url(r'^(?P<question_id>[0-9]+)/votes/$', views.votes, name='votes')
]

projects/mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('home.urls'))
]

projects/mysite/home/models.py
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
class Question(models.Model):
	question_text=models.CharField(max_length=200)
	pub_date=models.DateTimeField('data published')
	last_modified_date=models.DateTimeField('date modified',default=timezone.now())

	def __str__(self):
	 	return self.question_text
	# def last_updated(self):
	# 	return timezone.localtime(timezone.now())
	def  was_published_recently(self):
		return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

class SubQuestion(models.Model):
	question=models.ForeignKey(Question, on_delete=models.CASCADE)
	question_text=models.CharField(max_length=200)
	pub_date=models.DateTimeField('date published')
	last_modified_date=models.DateTimeField('date modified',default=timezone.now())

	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
	question=models.ForeignKey(SubQuestion, on_delete=models.CASCADE)
	choice_text=models.CharField(max_length=200)
	votes=models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

		

projects/mysite/home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse
from django.template import loader
from .models import Question, Choice

# Create your views here.
def index(request):
	latest_question_list=Question.objects.order_by('id')[:10]
	#template=loader.get_template('home/index.html')
	context={
		'latest_question_list':latest_question_list
	}
	return render(request,'home/index.html',context)

def details(request, question_id):
	question=get_object_or_404(Question, pk=question_id)
	return render(request, 'home/details.html', {'question':question})

def results(request, question_id):
	response="You're looking at the results of question %s"
	return HttpResponse(response%question_id)

def votes(request, question_id):
	return HttpResponse("You're voting on questions %s" % question_id)

projects/mysite/home/templates/home/details.html
<h1> {{question.question_text}} </h1>

{% if error_message %}<p style="font-weight: bolder;">{{error_message}}</p>
{% endif %}

<form action="{% url 'home:votes' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="{{forloop.counter}}" value="choice.id"/>
		<label for="choice:{{forloop.counter}}" style="font-family: Arial; font-weight: bolder;">{{choice.choice_text}}</label><br/>
	{% endfor %}
	<input type="submit" value="Choose"/>
</form>

projects/mysite/home/templates/home/index.html
{% if latest_question_list %}
	<style type="text/css">
	body{
		background-image: url('imgs/home_back.jpg');
		background-color: #cccccc;
	}
	</style>
	<ul style="font-size: 22px">
		{% for q in latest_question_list %}
			<li><a href="{% url 'home:details' q.id %}">{{q.question_text}}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No questions available!</p>
{% endif %}