projects/django-polls/polls/urls.py
from django.conf.urls import url

from . import views
app_name='polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/result/$', views.ResultView.as_view(), name='result'),
    url(r'^(?P<question_id>\d+)/vote/$',views.vote, name='vote'),
]

projects/django-polls/polls/models.py
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
# 

class Question(models.Model):
	#item=models.ForeignKey(Item, on_delete=models.CASCADE)
	question_text=models.CharField(max_length=200)
	publish_date=models.DateTimeField('date published', default=timezone.now())
	last_modified_date=models.DateTimeField('date modified')

	def __str__(self):
		return self.question_text
	def was_last_modified(self):
		now=timezone.now()
		return now-datetime.timedelta(days=1)<=self.last_modified_date<=now
	was_last_modified.admin_order_field='last_modified_date'
	was_last_modified.boolean=True
	was_last_modified.short_description="Modified recently?"

class Choice(models.Model):
	question=models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text=models.CharField(max_length=200)
	votes=models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

projects/django-polls/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.
class IndexView(generic.ListView):
	template_name='polls/index.html'
	context_object_name='question_list'

	def get_queryset(self):
		return Question.objects.filter(last_modified_date__lte=timezone.now()).order_by('-last_modified_date')[:10]

class DetailView(generic.DetailView):
	model=Question
	template_name='polls/detail.html'

	def get_queryset(self):
		return Question.objects.filter(last_modified_date__lte=timezone.now())

class ResultView(generic.DetailView):
	model=Question
	template_name='polls/result.html'

def vote(request, question_id):
	#item=get_object_or_404(Item, pk=item_id)
	question=get_object_or_404(Question, pk=question_id)
	try:
		selected_choice=question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html',{
			'question':question,
			'error_message': "You haven't chosen yet.",
			})
	else:
		selected_choice.votes+=1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:result',args=(question.id,)))


# def test(request, question_id):
# 	item=get_object_or_404(Item, pk=item_id)
# 	question_set=Question.objects.filter(item_id=item_id)
# 	size=question_set.count
# 	return render(request, 'polls/test.html',{'question':question_set,'size':size})

projects/django-polls/polls/templates/polls/detail.html
<h1>{{question.question_text}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token%}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" value="{{choice.id}}" id="choice{{forloop.counter}}"/>
		<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label></br>
	{% endfor %}
	<input type="reset" value="Clear" />
	<input type="submit" value="Submit" />
</form>

projects/django-polls/polls/templates/polls/index.html
<html>
<h1 style="margin-top: 0; position: center; ">Welcome to Haochen's survey</h1>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
<body>
{% if question_list %}
	<ul style="font-family: Arial; font-size: 22px">
	{% for question in question_list %}
		<li><a href="{% url 'polls:detail' question.id%}" style="color: green">{{question.question_text}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls available.</p>
{% endif %}</body>
</html>

projects/django-polls/polls/templates/polls/item.html
<html>
<h1>{{item.item_text}}</h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p>
{% endif %}
<form action="{% url 'polls:result' item.id %}" method="post" name="education">
{% csrf_token %}
<table>
	{% for question in item.question_set.all %}
		<h2 style="font-weight: bolder;font-size: 22px">{{question.question_text}}</h2>
		<script type="text/javascript">
			function is_checked(idx){
				var selectedChoice=document.getElementsByName(idx);
				for(var i=0; i<selectedChoice.length; i++){
					if(selectedChoice[i].checked) {
						break;
					}
				}
			}
		</script>
		{% for choice in question.choice_set.all %}
			<input type="radio" name="{{question.id}}" value="choice" id="choice{{forloop.counter}}" onclick="is_checked({{question.id}});">
			<!-- <label for="choice:{{forloop.counter}}" style="font-family: Arial;">{{choice.choice_text}}</label> -->{{choice.choice_text}}<br/>
		{% endfor %}
		<hr>
	{% endfor %}
	</table>
</br>
<input type="reset" value="Clear"/>
<input type="submit" value="Submit"/></form>
</html>

projects/django-polls/polls/templates/polls/question.html
<h1>{{question.question_text}}</h1>

{% if error_message %}<p>{{error_message}}</p>{% endif %}

projects/django-polls/polls/templates/polls/result.html
<p style="font-size: 22px; font-weight: bolder;">Result: "{{question.question_text}}"</p>
<ul>
{% for choice in question.choice_set.all %}
	<li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes | pluralize}} </li>
{% endfor %}
</ul>
<!-- <p class="reusltview"><a href="{% url 'polls:detail' question.id%}">survey again</a></p> -->
<form class="resultview" action="{% url 'polls:detail' question.id %}">{%csrf_token%}<input type="submit" value="Survey again"/></form>

projects/django-polls/polls/templates/polls/test.html
{% for q in question %}
	<p>{{q.question_text}}</p>
{% endfor %}
<p>{{size}}</p>